package com.jagex.runescape377.config;

public enum IncomingPacket
{
	REMOVE_LANDSCAPE_OBJECT(88),
	SET_LANDSCAPE_OBJECT(152),
	REMOVE_GROUND_ITEM(208),
	UPDATE_GROUND_ITEM_AMOUNT(121),
	SET_GROUND_ITEM(107),
	SET_PLAYER_GROUND_ITEM(106),
	UPDATE_GROUND_ITEMS_AND_LANDSCAPE_OBJECTS(183),
	CLEAR_GROUND_ITEMS_AND_LANDSCAPE_OBJECTS(40),

	SHOW_STILL_GRAPHICS(59),
	SHOW_PROJECTILE(181),
	SHOW_HINT_ICON(199),

	PLAY_SOUND(26),
	PLAY_POSITION_SOUND(41),
	PLAY_SONG(220),
	PLAY_TEMP_SONG(249),

	SYSTEM_UPDATE(190),
	CHATBOX_MESSAGE(63),

	CONSTRUCT_MAP_REGION(53),
	UPDATE_ACTIVE_MAP_REGION(222),

	SET_WIDGET_ANIMATION(2),
	SET_WIDGET_ITEM_MODEL(21),
	SET_WIDGET_PLAYER_HEAD(255),
	SET_CHAT_INPUT_TYPE_2(6),
	SET_WIDGET_MODEL_1(216),
	SET_WIDGET_MODEL_2(162),
	RESET_WIDGET_SETTINGS(113),
	FLASH_TAB_ICON(238),
	SET_TAB_WIDGET(10),
	SET_ACTIVE_TAB(252),
	CLEAR_WIDGET_ITEMS(219),
	UPDATE_ALL_WIDGET_ITEMS(206),
	UPDATE_WIDGET_ITEMS_BY_SLOT(134),
	UPDATE_WIDGET_SETTING_LARGE(115),
	UPDATE_WIDGET_SETTING_SMALL(182),
	UPDATE_CHAT_SETTINGS(201),
	UPDATE_WIDGET_COLOR(218),
	UPDATE_WIDGET_STRING(232),
	UPDATE_WIDGET_SCROLL_POSITION(200),
	UPDATE_WIDGET_MODEL_DISPLAY(186),
	HIDE_WIDGET(82),
	UPDATE_WIDGET_POSITION(166),
	SHOW_SIDEBAR_OVERLAY_WIDGET(246),
	SHOW_GAME_WIDGET(159),
	SHOW_SIDEBAR_AND_GAME_WIDGET(128),
	SHOW_WALKABLE_WIDGET(50),
	UPDATE_WELCOME_SCREEN(76),
	SHOW_DIALOG(158),
	SHOW_CHATBOX_WIDGET(109),
	SHOW_FULLSCREEN_WIDGET(253),
	CLOSE_ALL_WIDGETS(29),
	SET_MINIMAP_STATE(156),

	PLAYER_UPDATING(90),
	NPC_UPDATING(71),
	RESET_MOB_ANIMATIONS(13),

	UPDATE_FRIEND_LIST_STATUS(251),
	UPDATE_IGNORE_LIST(226),
	PRIVATE_MESSAGE_RECEIVED(135),
	UPDATE_FRIEND(78),
	UPDATE_PLAYER_CONTEXT_OPTION(157),

	SEND_REFERENCE_POSITION(75),

	UPDATE_MEMBERSHIP_AND_WORLD_INDEX(126),
	UPDATE_RUN_ENERGY(125),
	UPDATE_SKILL(49),
	UPDATE_CARRY_WEIGHT(174),
	SEND_LOGOUT(5),

	RESET_CUTSCENE_CAMERA(148),
	MOVE_CUTSCENE_CAMERA(167),
	CAMERA_SHAKE(67);

	private int packetId;

	IncomingPacket(int packetId)
	{
		this.packetId = packetId;
	}

	public int getId()
	{
		return packetId;
	}

	public boolean equals(int opcode)
	{
		return opcode == this.packetId;
	}
}